spring:
  application:
    name: harvest
  environment: mylocal
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      idle-timeout: 60000
      connection-timeout: 60000
      max-lifetime: 60000
      maximum-pool-size: 200
      minimum-idle: 10
      validation-timeout: 3000
      login-timeout: 5
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/harvest?useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
      username: root
      password:
    pingcap:
      jdbc-url: jdbc:mysql://localhost:3306/harvest?useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
      username: root
      password:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    password:
    timeout: 300
    jedis:
      pool:
        max-idle: -1
        max-wait:
mybatis:
  check-config-location: false
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/*.xml

logging:
  appname: /usr/local/var/www/java_log/
  config: classpath:logback-spring.xml
  level:
    root: error
    org:
      springframework: error
    com:
      contract:
        harvest: info

huobi:
  api_key: 1f708bc3-ntmuw4rrsr-df2c9550-4fd35
  secret_key: 8d462a2a-c794bf84-d84835d2-e5d67