spring:
  application:
    name: harvest
  environment: mylocal
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      idle-timeout: 60000
      connection-timeout: 60000
      max-lifetime: 60000
      maximum-pool-size: 200
      minimum-idle: 10
      validation-timeout: 3000
      login-timeout: 5
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/harvest?useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
      username: root
      password:
    pingcap:
      jdbc-url: jdbc:mysql://localhost:3306/harvest?useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
      username: root
      password:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    password:
    timeout: 300
    lettuce:
      pool:
        max-idle: -1 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 50 # 连接池最大连接数（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
  mail:
    host: smtp.qq.com
    protocol: smtp
    username: xxxx@foxmail.com
    password: xxxx
    properties:
      smtp:
        auth: false
        starttls:
          enable: false
          required: false
      mail:
        smtp:
          ssl:
            enable: true
mybatis:
  check-config-location: false
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/*.xml

logging:
  appname: /usr/local/var/www/java_log/
  config: classpath:logback-spring.xml
  level:
    root: error
    org:
      springframework: error
    com:
      contract:
        harvest: info

huobi:
  api_key: xxxx
  secret_key: xxxx
