spring:
  application:
    name: harvest
  environment: mybeta
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      idle-timeout: 60000
      connection-timeout: 60000
      max-lifetime: 60000
      maximum-pool-size: 200
      minimum-idle: 10
      validation-timeout: 3000
      login-timeout: 5
    mysql:
      jdbc-url: jdbc:mysql://149.129.80.230:3306/harvest?useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: iphone5C,.
    pingcap:
      jdbc-url: jdbc:mysql://149.129.80.230:3306/harvest?useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: iphone5C,.
  redis:
    host: 149.129.80.230
    port: 6379
    database: 1
    password: iphone5C,.
    timeout: 10000
    lettuce:
      pool:
        max-idle: -1 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 50 # 连接池最大连接数（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
mybatis:
  check-config-location: false
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/*.xml

logging:
#  appname: /home/docker/logs/
  appname: /usr/local/var/www/java_log/
  config: classpath:logback-spring.xml
  level:
    root: error
    org:
      springframework: error
    com:
      contract:
        harvest: info

#huobi:
#  api_key: 0fb32fd1-697ea0e8-1hrfj6yhgg-453e0
#  secret_key: 375ac040-22d27b91-0a622abf-68e1d

huobi:
  api_key: 25cd197d-e1ea52a2-3d2xc4v5bu-d1c27
  secret_key: 3c78ba15-14bdb083-d60a4757-b1021